# Generated by Django 5.0.1 on 2024-01-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
